### PR TITLE
Making node id optional for all issue commands (except branch)

### LINKED ISSUE #53: UX: Making node ID and project name (ID) optional
Currently all issue and project commands has mandatory ID argument. I think it would be much more user-friendly if the context was used to try set these IDs if arguments are missing:

- Issue commands can check if current branch name starts with "digits-" and use these digits as NID. If  not found and argument missing, abort with friendly error.
- Project commands can check if current directory is inside modules/ (not core/modules) and use directory name as ID. If  not found and argument missing, abort with friendly error.This depends on a fix for #52.

I can write a patch if this seems like a good idea to you too.

### PR DESCRIPTION
**Pull request by hansfn**
Partially fixes #53. 

If I get time, I'll do the same for project name.

### CODE REVIEW

**Comment by mglaman** [comment]
Rebased against `master` to fix conflicts. Making a few changes. I think it's fine to always have IssueCommandBase run `initRepo` instead of conditionally running it again in each command. Cleans things up a little.

**Comment by mglaman** [comment]
@hansfn want to give my changes a spin? Then we can merge and follow up with improving the Git repository detection

**Comment by hansfn** [comment]
The changes are fine - just merge them.  (I see I forgot to use initRepo in Apply::initialize.)

The reason I kept initRepo in the specific command subclasses was to be able to keep one feature of the link command - it worked without a local repo. I don't mind loosing that feature. (I have defined search engines in Chrome with keyword "don" - drupal.ord/node/%s -  so I just type "don NID" in the address, anyway.)

**Comment by mglaman** [comment]
Ah, yeah I didn't think about that for link. I'll just merge and open a follow up issue.

**Pull request merged**
