### PR TITLE
Replace gitter by GitPhp

### LINKED ISSUE #170: Uncaught TypeError Argument 1
I cleaned out my .config folder completely and installed drupalorg cli fresh

When I run drupalorg MRN I get this error on PHP 7.4.

User error maybe?

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in /home/me/.config/composer/vendor/klaussilveira/gitter/lib/Gitter/Client.php on line 82 and defined in /home/me/.config/composer/vendor/symfony/process/Process.php:143

### PR DESCRIPTION
**Pull request by chrfritsch**
Fixes #170

### CODE REVIEW

**Comment by NickDickinsonWilde** [comment]
+1 this fixes RN and would be really nice to have merged and a new release made

**Comment by jhedstrom** [comment]
Confirmed this resolves the issue.

**Comment by kekkis** [comment]
I also tested this with a global composer.json as follows:
```
{
    "repositories": {
        "mglaman/drupalorg-cli": {
            "type": "vcs",
            "url": "https://github.com/chrfritsch/drupalorg-cli.git"
        }
    },
    "require": {
        "mglaman/drupalorg-cli": "dev-replace-gitter"
    }
}
```

Like for @jhedstrom, the issue is no longer present and the `rn` command works again.

**Review by mglaman — APPROVED** [review]
Thanks all, and for your patience!

**Pull request merged**
