### PR TITLE
Light improvements to maintainer:release-notes

### PR DESCRIPTION
**Pull request by damienmckenna**
This is for #21.

* Removed the "summary" line.
* Added a filler piece to suggest that the maintainers should add some summary text.
* Added a "full changelog" heading.
* Indented LI tags.

### CODE REVIEW

**Comment by mglaman** [comment]
Rebased to fix conflict.

**Comment by mglaman** [comment]
Test Commerce 2.6 output

---

/Add a summary here/

**Contributors**: (31) czigor, Sophie.SK, bojanz, pslcbs, jsacksick, quietone, mglaman, caseylau, Lendude, drugan, skek, AndreaMaggi, ransomweaver, ndf, Londova, Dom., lisastreeter, FatherShawn, abramm, xSDx, joachim, waspper, agoradesign, tce, karlos007, trigdog, joe1987uk, shabana.navas, sorabh.v6, alianov, Kate Heinlein

**Issues**: 32 issues resolved.

### Full changelog

Changes since [8.x-2.5](https://www.drupal.org/project/commerce/releases/8.x-2.5):

#### Bug

* [#2958865](https://www.drupal.org/node/2958865) by [czigor](https://www.drupal.org/u/czigor): Call to undefined method Drupal\commerce_payment\PaymentOptionsBuilder::t()
* [#2946909](https://www.drupal.org/node/2946909) by [Sophie.SK](https://www.drupal.org/u/sophie.sk), [bojanz](https://www.drupal.org/u/bojanz): When a payment gateway error occurs, the order does not become unocked
* [#2944310](https://www.drupal.org/node/2944310) by [quietone](https://www.drupal.org/u/quietone), [bojanz](https://www.drupal.org/u/bojanz): Fatal error from views_data_alter during migration
* [#2509702](https://www.drupal.org/node/2509702) by [jsacksick](https://www.drupal.org/u/jsacksick), [bojanz](https://www.drupal.org/u/bojanz): Inline errors look terrible on the price field
* [#2939008](https://www.drupal.org/node/2939008) by [jsacksick](https://www.drupal.org/u/jsacksick): There is no formatter for the commerce_plugin_item field type
* [#2956944](https://www.drupal.org/node/2956944) by [bojanz](https://www.drupal.org/u/bojanz): [Regression] PreparedAttribute doesn't accept optional attributes
* [#2956043](https://www.drupal.org/node/2956043) by [bojanz](https://www.drupal.org/u/bojanz): ProductVariationAttributeMapper::selectVariation() returns the first variation, not the default one
* [#2956095](https://www.drupal.org/node/2956095) by [caseylau](https://www.drupal.org/u/caseylau): Disable "Allow users to add existing variations."
* [#2879869](https://www.drupal.org/node/2879869) by [Lendude](https://www.drupal.org/u/lendude), [bojanz](https://www.drupal.org/u/bojanz): Fatal error when trying to save a View with a filters using an attribute
* [#2707721](https://www.drupal.org/node/2707721) by [drugan](https://www.drupal.org/u/drugan), [mglaman](https://www.drupal.org/u/mglaman), [skek](https://www.drupal.org/u/skek), [AndreaMaggi](https://www.drupal.org/u/andreamaggi), [ransomweaver](https://www.drupal.org/u/ransomweaver): Incorrect display of attribute field values on the Add To Cart form
* [#2900772](https://www.drupal.org/node/2900772) by [FatherShawn](https://www.drupal.org/u/fathershawn), [abramm](https://www.drupal.org/u/abramm), [bojanz](https://www.drupal.org/u/bojanz): The payment method entity type is not exposed to Views
* [#2882374](https://www.drupal.org/node/2882374) by [xSDx](https://www.drupal.org/u/xsdx), [Lendude](https://www.drupal.org/u/lendude), [drugan](https://www.drupal.org/u/drugan), [bojanz](https://www.drupal.org/u/bojanz): Views filters are broken for price fields ("number" column)
* [#2955241](https://www.drupal.org/node/2955241): Plugin label 'order item table' should be in sentence case
* [#2951181](https://www.drupal.org/node/2951181) by [joachim](https://www.drupal.org/u/joachim), [bojanz](https://www.drupal.org/u/bojanz): QuantityWidget allows "0" as a valid value
* [#2897813](https://www.drupal.org/node/2897813) by [waspper](https://www.drupal.org/u/waspper), [bojanz](https://www.drupal.org/u/bojanz): Remove the 'access cart' permission because it is unused and not granular enough
* [#2944402](https://www.drupal.org/node/2944402) by [bojanz](https://www.drupal.org/u/bojanz), [agoradesign](https://www.drupal.org/u/agoradesign), [tce](https://www.drupal.org/u/tce): Cart totals are not updated when clicking the "Checkout" button
* [#2954205](https://www.drupal.org/node/2954205) by [abramm](https://www.drupal.org/u/abramm): Missing $order_item->getTotalPrice() return value check
* [#2861983](https://www.drupal.org/node/2861983) by [trigdog](https://www.drupal.org/u/trigdog), [joe1987uk](https://www.drupal.org/u/joe1987uk), [drugan](https://www.drupal.org/u/drugan), [shabana.navas](https://www.drupal.org/u/shabana.navas), [sorabh.v6](https://www.drupal.org/u/sorabh.v6), [bojanz](https://www.drupal.org/u/bojanz): Improve cart behavior when the quantity is 0 or an empty string
* [#2953843](https://www.drupal.org/node/2953843) by [quietone](https://www.drupal.org/u/quietone): Make product body field translatable
* [#2953599](https://www.drupal.org/node/2953599) by [agoradesign](https://www.drupal.org/u/agoradesign): Wrong return type in DocBlock for getPluginConfiguration() of payment gateways and tax types
* [#2952849](https://www.drupal.org/node/2952849) by [Lendude](https://www.drupal.org/u/lendude): Random test fail in Drupal\Tests\commerce_promotion\FunctionalJavascript\CouponTest

#### Feature

* [#2953940](https://www.drupal.org/node/2953940) by [pslcbs](https://www.drupal.org/u/pslcbs), [jsacksick](https://www.drupal.org/u/jsacksick), [bojanz](https://www.drupal.org/u/bojanz): Add an OrderPaymentGateway condition
* [#2951353](https://www.drupal.org/node/2951353) by [mglaman](https://www.drupal.org/u/mglaman): Provide a Twig template and theme hook suggestions for checkout panes
* [#2853277](https://www.drupal.org/node/2853277) by [lisastreeter](https://www.drupal.org/u/lisastreeter): Populate OrderItem backreference to Order before OrderItem is saved

#### Task

* [#2858599](https://www.drupal.org/node/2858599) by [bojanz](https://www.drupal.org/u/bojanz): Move a portion of the PaymentInformation pane logic to a PaymentOptionsBuilder
* [#2865324](https://www.drupal.org/node/2865324) by [Dom.](https://www.drupal.org/u/dom.), [bojanz](https://www.drupal.org/u/bojanz): Make the commerce_order_item "created" field configurable on view displays
* [#2953937](https://www.drupal.org/node/2953937) by [agoradesign](https://www.drupal.org/u/agoradesign): Clean up PriceCalculatedFormatter variables
* [#2954572](https://www.drupal.org/node/2954572) by [karlos007](https://www.drupal.org/u/karlos007): Update composer.json to indicate the minimum required Entity API version
* [#2949406](https://www.drupal.org/node/2949406) by [alianov](https://www.drupal.org/u/alianov), [bojanz](https://www.drupal.org/u/bojanz), [Kate Heinlein](https://www.drupal.org/u/kate-heinlein): Make CountryRepository exchangeable in CreateStoreCommand class
* [#2953865](https://www.drupal.org/node/2953865) by [alianov](https://www.drupal.org/u/alianov): Move PaymentMethodAccessCheck to a different namespace

**Comment by mglaman** [comment]
HTML output

```
<p><em>Add a summary here</em></p>
<p><strong>Contributors:</strong> (31) czigor, Sophie.SK, bojanz, pslcbs, jsacksick, quietone, mglaman, caseylau, Lendude, drugan, skek, AndreaMaggi, ransomweaver, ndf, Londova, Dom., lisastreeter, FatherShawn, abramm, xSDx, joachim, waspper, agoradesign, tce, karlos007, trigdog, joe1987uk, shabana.navas, sorabh.v6, alianov, Kate Heinlein</p>
<p><strong>Issues:</strong> 32 issues resolved.</p>
<h3>Full changelog</h3>
<p>Changes since <a href="https://www.drupal.org/project/commerce/releases/8.x-2.5">8.x-2.5</a>:</p>
<h4>Bug</h4>
<ul>
  <li><a href="https://www.drupal.org/node/2958865">#2958865</a> by <a href="https://www.drupal.org/u/czigor">czigor</a>: Call to undefined method Drupal\commerce_payment\PaymentOptionsBuilder::t()</li>
  <li><a href="https://www.drupal.org/node/2946909">#2946909</a> by <a href="https://www.drupal.org/u/sophie.sk">Sophie.SK</a>, <a href="https://www.drupal.org/u/bojanz">bojanz</a>: When a payment gateway error occurs, the order does not become unocked</li>
  <li><a href="https://www.drupal.org/node/2944310">#2944310</a> by <a href="https://www.drupal.org/u/quietone">quietone</a>, <a href="https://www.drupal.org/u/bojanz">bojanz</a>: Fatal error from views_data_alter during migration</li>
  <li><a href="https://www.drupal.org/node/2509702">#2509702</a> by <a href="https://www.drupal.org/u/jsacksick">jsacksick</a>, <a href="https://www.drupal.org/u/bojanz">bojanz</a>: Inline errors look terrible on the price field</li>
  <li><a href="https://www.drupal.org/node/2939008">#2939008</a> by <a href="https://www.drupal.org/u/jsacksick">jsacksick</a>: There is no formatter for the commerce_plugin_item field type</li>
  <li><a href="https://www.drupal.org/node/2956944">#2956944</a> by <a href="https://www.drupal.org/u/bojanz">bojanz</a>: [Regression] PreparedAttribute doesn't accept optional attributes</li>
  <li><a href="https://www.drupal.org/node/2956043">#2956043</a> by <a href="https://www.drupal.org/u/bojanz">bojanz</a>: ProductVariationAttributeMapper::selectVariation() returns the first variation, not the default one</li>
  <li><a href="https://www.drupal.org/node/2956095">#2956095</a> by <a href="https://www.drupal.org/u/caseylau">caseylau</a>: Disable "Allow users to add existing variations."</li>
  <li><a href="https://www.drupal.org/node/2879869">#2879869</a> by <a href="https://www.drupal.org/u/lendude">Lendude</a>, <a href="https://www.drupal.org/u/bojanz">bojanz</a>: Fatal error when trying to save a View with a filters using an attribute</li>
  <li><a href="https://www.drupal.org/node/2707721">#2707721</a> by <a href="https://www.drupal.org/u/drugan">drugan</a>, <a href="https://www.drupal.org/u/mglaman">mglaman</a>, <a href="https://www.drupal.org/u/skek">skek</a>, <a href="https://www.drupal.org/u/andreamaggi">AndreaMaggi</a>, <a href="https://www.drupal.org/u/ransomweaver">ransomweaver</a>: Incorrect display of attribute field values on the Add To Cart form</li>
  <li><a href="https://www.drupal.org/node/2900772">#2900772</a> by <a href="https://www.drupal.org/u/fathershawn">FatherShawn</a>, <a href="https://www.drupal.org/u/abramm">abramm</a>, <a href="https://www.drupal.org/u/bojanz">bojanz</a>: The payment method entity type is not exposed to Views</li>
  <li><a href="https://www.drupal.org/node/2882374">#2882374</a> by <a href="https://www.drupal.org/u/xsdx">xSDx</a>, <a href="https://www.drupal.org/u/lendude">Lendude</a>, <a href="https://www.drupal.org/u/drugan">drugan</a>, <a href="https://www.drupal.org/u/bojanz">bojanz</a>: Views filters are broken for price fields ("number" column)</li>
  <li><a href="https://www.drupal.org/node/2955241">#2955241</a>: Plugin label 'order item table' should be in sentence case</li>
  <li><a href="https://www.drupal.org/node/2951181">#2951181</a> by <a href="https://www.drupal.org/u/joachim">joachim</a>, <a href="https://www.drupal.org/u/bojanz">bojanz</a>: QuantityWidget allows "0" as a valid value</li>
  <li><a href="https://www.drupal.org/node/2897813">#2897813</a> by <a href="https://www.drupal.org/u/waspper">waspper</a>, <a href="https://www.drupal.org/u/bojanz">bojanz</a>: Remove the 'access cart' permission because it is unused and not granular enough</li>
  <li><a href="https://www.drupal.org/node/2944402">#2944402</a> by <a href="https://www.drupal.org/u/bojanz">bojanz</a>, <a href="https://www.drupal.org/u/agoradesign">agoradesign</a>, <a href="https://www.drupal.org/u/tce">tce</a>: Cart totals are not updated when clicking the "Checkout" button</li>
  <li><a href="https://www.drupal.org/node/2954205">#2954205</a> by <a href="https://www.drupal.org/u/abramm">abramm</a>: Missing $order_item->getTotalPrice() return value check</li>
  <li><a href="https://www.drupal.org/node/2861983">#2861983</a> by <a href="https://www.drupal.org/u/trigdog">trigdog</a>, <a href="https://www.drupal.org/u/joe1987uk">joe1987uk</a>, <a href="https://www.drupal.org/u/drugan">drugan</a>, <a href="https://www.drupal.org/u/shabana.navas">shabana.navas</a>, <a href="https://www.drupal.org/u/sorabh.v6">sorabh.v6</a>, <a href="https://www.drupal.org/u/bojanz">bojanz</a>: Improve cart behavior when the quantity is 0 or an empty string</li>
  <li><a href="https://www.drupal.org/node/2953843">#2953843</a> by <a href="https://www.drupal.org/u/quietone">quietone</a>: Make product body field translatable</li>
  <li><a href="https://www.drupal.org/node/2953599">#2953599</a> by <a href="https://www.drupal.org/u/agoradesign">agoradesign</a>: Wrong return type in DocBlock for getPluginConfiguration() of payment gateways and tax types</li>
  <li><a href="https://www.drupal.org/node/2952849">#2952849</a> by <a href="https://www.drupal.org/u/lendude">Lendude</a>: Random test fail in Drupal\Tests\commerce_promotion\FunctionalJavascript\CouponTest</li>
</ul>
<h4>Feature</h4>
<ul>
  <li><a href="https://www.drupal.org/node/2953940">#2953940</a> by <a href="https://www.drupal.org/u/pslcbs">pslcbs</a>, <a href="https://www.drupal.org/u/jsacksick">jsacksick</a>, <a href="https://www.drupal.org/u/bojanz">bojanz</a>: Add an OrderPaymentGateway condition</li>
  <li><a href="https://www.drupal.org/node/2951353">#2951353</a> by <a href="https://www.drupal.org/u/mglaman">mglaman</a>: Provide a Twig template and theme hook suggestions for checkout panes</li>
  <li><a href="https://www.drupal.org/node/2853277">#2853277</a> by <a href="https://www.drupal.org/u/lisastreeter">lisastreeter</a>: Populate OrderItem backreference to Order before OrderItem is saved</li>
</ul>
<h4>Task</h4>
<ul>
  <li><a href="https://www.drupal.org/node/2858599">#2858599</a> by <a href="https://www.drupal.org/u/bojanz">bojanz</a>: Move a portion of the PaymentInformation pane logic to a PaymentOptionsBuilder</li>
  <li><a href="https://www.drupal.org/node/2865324">#2865324</a> by <a href="https://www.drupal.org/u/dom.">Dom.</a>, <a href="https://www.drupal.org/u/bojanz">bojanz</a>: Make the commerce_order_item "created" field configurable on view displays</li>
  <li><a href="https://www.drupal.org/node/2953937">#2953937</a> by <a href="https://www.drupal.org/u/agoradesign">agoradesign</a>: Clean up PriceCalculatedFormatter variables</li>
  <li><a href="https://www.drupal.org/node/2954572">#2954572</a> by <a href="https://www.drupal.org/u/karlos007">karlos007</a>: Update composer.json to indicate the minimum required Entity API version</li>
  <li><a href="https://www.drupal.org/node/2949406">#2949406</a> by <a href="https://www.drupal.org/u/alianov">alianov</a>, <a href="https://www.drupal.org/u/bojanz">bojanz</a>, <a href="https://www.drupal.org/u/kate-heinlein">Kate Heinlein</a>: Make CountryRepository exchangeable in CreateStoreCommand class</li>
  <li><a href="https://www.drupal.org/node/2953865">#2953865</a> by <a href="https://www.drupal.org/u/alianov">alianov</a>: Move PaymentMethodAccessCheck to a different namespace</li>
</ul>
```

**Comment by damienmckenna** [comment]
Nice!

**Comment by damienmckenna** [comment]
I think it'd be worth changing this further so that the "contributors" section has a separate heading, and the issue count is part of the "full changelog" section.

**Comment by damienmckenna** [comment]
I've updated the output a bit more, let me know what you think.

**Comment by mglaman** [comment]
@damienmckenna I'll review in full, but I like it from the diff

**Comment by mglaman** [comment]
/Add a summary here/

### Contributors (31)

czigor, Sophie.SK, bojanz, pslcbs, jsacksick, quietone, mglaman, caseylau, Lendude, drugan, skek, AndreaMaggi, ransomweaver, ndf, Londova, Dom., lisastreeter, FatherShawn, abramm, xSDx, joachim, waspper, agoradesign, tce, karlos007, trigdog, joe1987uk, shabana.navas, sorabh.v6, alianov, Kate Heinlein

### Full changelog

**Issues**: 32 issues resolved.

Changes since [v8.x-2.5](https://www.drupal.org/project/commerce/releases/8.x-2.5):

#### Bug

* [#2958865](https://www.drupal.org/node/2958865) by [czigor](https://www.drupal.org/u/czigor): Call to undefined method Drupal\commerce_payment\PaymentOptionsBuilder::t()
* [#2946909](https://www.drupal.org/node/2946909) by [Sophie.SK](https://www.drupal.org/u/sophie.sk), [bojanz](https://www.drupal.org/u/bojanz): When a payment gateway error occurs, the order does not become unocked
* [#2944310](https://www.drupal.org/node/2944310) by [quietone](https://www.drupal.org/u/quietone), [bojanz](https://www.drupal.org/u/bojanz): Fatal error from views_data_alter during migration
* [#2509702](https://www.drupal.org/node/2509702) by [jsacksick](https://www.drupal.org/u/jsacksick), [bojanz](https://www.drupal.org/u/bojanz): Inline errors look terrible on the price field
* [#2939008](https://www.drupal.org/node/2939008) by [jsacksick](https://www.drupal.org/u/jsacksick): There is no formatter for the commerce_plugin_item field type
* [#2956944](https://www.drupal.org/node/2956944) by [bojanz](https://www.drupal.org/u/bojanz): [Regression] PreparedAttribute doesn't accept optional attributes
* [#2956043](https://www.drupal.org/node/2956043) by [bojanz](https://www.drupal.org/u/bojanz): ProductVariationAttributeMapper::selectVariation() returns the first variation, not the default one
* [#2956095](https://www.drupal.org/node/2956095) by [caseylau](https://www.drupal.org/u/caseylau): Disable "Allow users to add existing variations."
* [#2879869](https://www.drupal.org/node/2879869) by [Lendude](https://www.drupal.org/u/lendude), [bojanz](https://www.drupal.org/u/bojanz): Fatal error when trying to save a View with a filters using an attribute
* [#2707721](https://www.drupal.org/node/2707721) by [drugan](https://www.drupal.org/u/drugan), [mglaman](https://www.drupal.org/u/mglaman), [skek](https://www.drupal.org/u/skek), [AndreaMaggi](https://www.drupal.org/u/andreamaggi), [ransomweaver](https://www.drupal.org/u/ransomweaver): Incorrect display of attribute field values on the Add To Cart form
* [#2900772](https://www.drupal.org/node/2900772) by [FatherShawn](https://www.drupal.org/u/fathershawn), [abramm](https://www.drupal.org/u/abramm), [bojanz](https://www.drupal.org/u/bojanz): The payment method entity type is not exposed to Views
* [#2882374](https://www.drupal.org/node/2882374) by [xSDx](https://www.drupal.org/u/xsdx), [Lendude](https://www.drupal.org/u/lendude), [drugan](https://www.drupal.org/u/drugan), [bojanz](https://www.drupal.org/u/bojanz): Views filters are broken for price fields ("number" column)
* [#2955241](https://www.drupal.org/node/2955241): Plugin label 'order item table' should be in sentence case
* [#2951181](https://www.drupal.org/node/2951181) by [joachim](https://www.drupal.org/u/joachim), [bojanz](https://www.drupal.org/u/bojanz): QuantityWidget allows "0" as a valid value
* [#2897813](https://www.drupal.org/node/2897813) by [waspper](https://www.drupal.org/u/waspper), [bojanz](https://www.drupal.org/u/bojanz): Remove the 'access cart' permission because it is unused and not granular enough
* [#2944402](https://www.drupal.org/node/2944402) by [bojanz](https://www.drupal.org/u/bojanz), [agoradesign](https://www.drupal.org/u/agoradesign), [tce](https://www.drupal.org/u/tce): Cart totals are not updated when clicking the "Checkout" button
* [#2954205](https://www.drupal.org/node/2954205) by [abramm](https://www.drupal.org/u/abramm): Missing $order_item->getTotalPrice() return value check
* [#2861983](https://www.drupal.org/node/2861983) by [trigdog](https://www.drupal.org/u/trigdog), [joe1987uk](https://www.drupal.org/u/joe1987uk), [drugan](https://www.drupal.org/u/drugan), [shabana.navas](https://www.drupal.org/u/shabana.navas), [sorabh.v6](https://www.drupal.org/u/sorabh.v6), [bojanz](https://www.drupal.org/u/bojanz): Improve cart behavior when the quantity is 0 or an empty string
* [#2953843](https://www.drupal.org/node/2953843) by [quietone](https://www.drupal.org/u/quietone): Make product body field translatable
* [#2953599](https://www.drupal.org/node/2953599) by [agoradesign](https://www.drupal.org/u/agoradesign): Wrong return type in DocBlock for getPluginConfiguration() of payment gateways and tax types
* [#2952849](https://www.drupal.org/node/2952849) by [Lendude](https://www.drupal.org/u/lendude): Random test fail in Drupal\Tests\commerce_promotion\FunctionalJavascript\CouponTest

#### Feature

* [#2953940](https://www.drupal.org/node/2953940) by [pslcbs](https://www.drupal.org/u/pslcbs), [jsacksick](https://www.drupal.org/u/jsacksick), [bojanz](https://www.drupal.org/u/bojanz): Add an OrderPaymentGateway condition
* [#2951353](https://www.drupal.org/node/2951353) by [mglaman](https://www.drupal.org/u/mglaman): Provide a Twig template and theme hook suggestions for checkout panes
* [#2853277](https://www.drupal.org/node/2853277) by [lisastreeter](https://www.drupal.org/u/lisastreeter): Populate OrderItem backreference to Order before OrderItem is saved

#### Task

* [#2858599](https://www.drupal.org/node/2858599) by [bojanz](https://www.drupal.org/u/bojanz): Move a portion of the PaymentInformation pane logic to a PaymentOptionsBuilder
* [#2865324](https://www.drupal.org/node/2865324) by [Dom.](https://www.drupal.org/u/dom.), [bojanz](https://www.drupal.org/u/bojanz): Make the commerce_order_item "created" field configurable on view displays
* [#2953937](https://www.drupal.org/node/2953937) by [agoradesign](https://www.drupal.org/u/agoradesign): Clean up PriceCalculatedFormatter variables
* [#2954572](https://www.drupal.org/node/2954572) by [karlos007](https://www.drupal.org/u/karlos007): Update composer.json to indicate the minimum required Entity API version
* [#2949406](https://www.drupal.org/node/2949406) by [alianov](https://www.drupal.org/u/alianov), [bojanz](https://www.drupal.org/u/bojanz), [Kate Heinlein](https://www.drupal.org/u/kate-heinlein): Make CountryRepository exchangeable in CreateStoreCommand class
* [#2953865](https://www.drupal.org/node/2953865) by [alianov](https://www.drupal.org/u/alianov): Move PaymentMethodAccessCheck to a different namespace

**Pull request merged**
